### ISSUE TITLE
Savon.expects doesn't work if there are more than one expectations in a spec  

### ISSUE THREAD

**Issue by jedbeard** [savonrb/savon_spec#15]
Hi Daniel,

if i write a spec which has two savon expectations i get 

``` ruby
Savon::Spec::ExpectationError:
       expected :second_action to be called, got: :first_action
```

if i change the expectations order i get this

``` ruby
Savon::Spec::ExpectationError:
       expected :first_action to be called, got: :second_action
```

WHY, whats happend from savon_spec 0.9.\* to 1.3.\* ??

``` ruby
before do 
  savon.expects(:first_action).returns(:simple)
  savon.expects(:second_action).returns(:alina)
end

it "should bla" do
  call something with first calls first_action and then second action
end
```

**Comment by weidenfreak** [comment]
Did some debugging and I think I finally have an assumption why it's not working. see: https://github.com/weidenfreak/savon_spec/compare/a6fdac78c7...e5a9fb12c3

In the debugging.rb file I tried to extract the not working behaviour into a minimal example. Don't know if that's of any help for @rubiii but i learned a lot :)

Would love to fix this myself but this would probably take ages if try this on my own :(

**Comment by egilburg** [comment]
I don't have a solution for having several expectations AT ONCE, but if you have a procedural test that can mock one response, test it, then mock another one instead, then you can use the following line before each expects statement.

In older Savon versions:

``` ruby
Savon.config.hooks.hooks = nil
```

In the latest Savon version:

``` ruby
[ :spec_action, :spec_response ].each { |id| Savon.config.hooks.reject(id) }
```

(I think SavonSpec should provide a method `reset_expectations` or `reset_mocks` which does the above).

This will reset the previous mocks.

**Comment by rubiii** [comment]
this should work with savon 2.0. i just [pushed some documentation](http://savonrb.com/version2.html#testing). please give it a try.

**Comment by HarishAtGitHub** [comment]
I have the same problem ...Is there any possibility to make this work with savon 1.1.0 ? . I am tied to that version as a library I am using needs that version only ..
