### ISSUE TITLE
Inconsistency with expectations due to the implementation of Savon hooks

### ISSUE THREAD

**Issue by timabdulla** [savonrb/savon_spec#17]
Let me detail an interesting problem I just encountered, though I am not sure of the best way to go about correcting it. This issue touches on both savon and savon_spec, but I encountered it while using savon_spec, so I will document it here. 

A basic summary is that there is inconsistent behaviour when using `Savon::Spec::Mock#expects` because of how Savon itself implements hooks. If in my first test I initialize a Savon client using `Savon::Client::new` and then add an expectation using `savon.expects`, my expectation will be ignored, and Savon will normally process my next SOAP request. However, on all subsequent tests, if I follow the same workflow (initialize a client, then add an expectation), my expectation will not be ignored, and my next SOAP request will be handled by the mock. This behaviour is inconsistent, and it was very confusing for me to debug. 

This occurs because of how hooks are implemented in Savon. The first client I initialize will clone `Savon::config`. Initially, `@hooks` in `Savon::config` will be `nil`, so this instance variable will not be copied to my clone of `Savon::config`. When I set an expectation using `savon.expects`, the hooks are added to `@hooks` in `Savon::config`. These changes are not, however, seen by the client I have already initialized. Therefore, when I call request on my client, it will make an HTTP request. 

Now let's assume I follow the exact same workflow for my next test. The second client I initialize will clone `Savon::config`, as before. However, this time, `@hooks` in `Savon::config` will not be nil. It will be a hook group with no hooks. This is because `@hooks` was initialized with a hooks group in my first test when I created an expectation. Therefore, my second client will copy the `@hooks` instance variable to its config object. Because clone only does a shallow copy, `@hooks` in `Savon::config` and `@hooks` in the second client are the same object. Therefore, when I call `savon.expects` to set up an expectation and it adds hooks to `@hooks` in `Savon::config`, it will be seen by the second client. Thus, when I call request on my client, the hooks will properly intercept my call, and the expectation will be triggered.

Here is an example of this: https://gist.github.com/3305938

Actually, it is not even required to create an expectation in the first test I run. If I run any example before my second example, even if this first example does not use Savon in any way, the second test will succeed. Why? Because Savon::Spec installs a hook that runs after each RSpec example. This hook's purpose is to clears out all the hooks currently installed in Savon. In doing this clearing, it initializes `@hooks` in Savon::config, thus creating the conditions that will allow the second test to succeed. Confusing, isn't it? :-)

This leads to me a few issues: 

1 - What is the desired behaviour of Savon hooks? If you instantiate a number of clients before `@hooks` in `Savon::config` has a value, and then instantiate a number of clients once it does have a value, the hooks are seen by the latter group but not the former. This is inconsistent and confusing behaviour. It seems to me that hooks should be seen by all Savon clients, unless there is an explicit desire for a client to ignore hooks or use its own group of hooks. 

2 - The examples in the docs only ever show the client being lazy initialized using a let block in rspec. This allows the example tests to work fine, because the client will not be initialized until after the expectation has been created. However, lazy initialization is very often not a viable option. I inject my Savon client into my object under test before the commencement of each example. I think is a fairly common pattern which will not work consistently with the current implementation. There is a simple workaround however: I just call `Savon::config.hooks` in my `before(:all)` block. When I call `Savon::config.hooks`, it initializes `@hooks`, and therefore the first client I create (and all subsequent clients) will have `@hooks` in their config objects set to the same object as `@hooks` in `Savon::config`. Obviously, this is not an ideal solution.

I'm not sure of the author's intention, but it seems that the hooks implementation is currently not very well defined in its behaviour. I won't submit a pull request, because I am not sure how the author desires hooks to work. I think that a hook group should be common across all clients. Either way, it doesn't make sense to make a hook group shared across only clients that have been created after a hook group has already been instantiated in `Savon::config`. 

I look forward to your comments.

Regards,

Tim Abdulla

**Comment by rubiii** [comment]
hey tim,

that's a really interesting issue. the reason why hooks are not really documented, is that i'm (still) not satisfied with how they are implemented. it somehow feels like the approach was a step into the wrong direction that provides too much coupling to external usage. the reason why i added the request hook to savon is to add a proper interface for savon_spec. as savon_spec is a separate library, it's kind of difficult to keep them in sync without it.

my idea for savon_spec is to somehow integrate it into savon and to get rid of the separation. i really like the idea of "eating your own dogfood" and if it's possible to integrate and use these spec helpers for savon's own specs, that would be awesome. i try to follow semver as much as possible, so hooks can not be removed from savon 1.x, but if savon_spec can be integrated into savon, the request hook could be removed from version 2.0 and replaced by some other solution for specific requirements (e.g. benchmarking) which are currently solved by this generic approach.

one obvious problem with integrating savon_spec is, that i feel like savon should not depend on any testing/mocking libraries. this could be "solved" by "optional dependencies", but it's obviously not the best solution. another problem is the tight coupling to rspec. i think this is ok for now and could be solved through some kind of abstraction to support e.g. minitest in the future though.

please let me know what you think.

cheers,
daniel

**Comment by rubiii** [comment]
this will be fixed with savon 2.0. please [read the documentation](http://savonrb.com/version2.html) and give it a try if you can.
