### ISSUE TITLE
[FEATURE REQUEST] Test the number of request

### ISSUE THREAD

**Issue by shingara** [savonrb/savon_spec#20]
Hi,

It can be good, to test the number of this request like mock library can do. By exemple :

``` ruby
savon.expects(:get_user).once
savon.expects(:get_user).twice
savon.expects(:get_user).at_least(x)
savon.expects(:get_user).exactly(x)
savon.expects(:get_user).at_most(x)
```

**Comment by rubiii** [comment]
that would be a nice feature, but it's not going to happen until somebody else implements it.
i'm more and more convinced of using a lightweight integration server for testing soap clients
and i'll hopefully have a general solution for this until [version 2](savonrb.com/version2.html).

thanks for the request.
