### ISSUE TITLE
Using Savon for request test of my Rails SOAP actions

### ISSUE THREAD

**Issue by foton** [savonrb/savon_spec#22]
Hi,
  i need to do Request RSpec testing of SOAP actions in my Rails app.
  Using Savon as klient seems nice, but I cannot set the correct path/uri to WSDL inside tests. These URIs do not work:

```
 wsdl=   "http://localhost:3000/soap/wsdl"
 wsdl = "http://www.example.com/soap/wsdl"
 wsdl=   "/soap/wsdl"
 @client = Savon.client(:wsdl => wsdl )
```

For more complex question see http://stackoverflow.com/questions/17185639/integration-request-rspec-test-of-my-soap-service.

Is there any way to do this?

**Comment by rubiii** [comment]
@foton i left a comment on your question on stackoverflow. let's continue this over there, as the issue tracker is not meant to used for support requests. also, your problem is to find the corrent host and port used by rails during functional tests. not related to savon at all. thanks.
