### ISSUE TITLE
README example code references undefined things

### ISSUE THREAD

**Issue by betelgeuse** [savonrb/savon_spec#3]
I stumbled upon this gem and started using the README. As far as I can see the example code relies on things that are not part of the code there. I was confused with these:
- User.client is not defined
- how :multiple_users and :single_user responses become User objects
  -  these come from fixture I think so the example code should also have the fixture files

**Comment by lgustafson** [comment]
When I started using this gem, I found the readme to be confusing for the same reasons.  I actually think the sample is based on the code found in the readme for "savon_model" (https://github.com/rubiii/savon_model).  That might help you understand this code.

The fixtures are simply raw xml responses that you use to mock usage of the savon gem.

**Comment by rubiii** [comment]
completely replaced the readme for v1.0.0. fork, edit and open a pull request if you think anything's missing.
